# Generated by Django 2.1.2 on 2018-11-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jarida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=4)),
                ('date', models.DateField(unique=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='loi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField()),
                ('objet', models.CharField(max_length=2000)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.jarida')),
            ],
        ),
    ]
