# Generated by Django 2.1.2 on 2018-11-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20181104_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='decret_executif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('objet', models.CharField(max_length=2000)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.loi')),
            ],
        ),
    ]
