# Generated by Django 2.1.2 on 2018-11-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_decret_executif'),
    ]

    operations = [
        migrations.AddField(
            model_name='decret_executif',
            name='loi',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_1.loi'),
        ),
        migrations.AlterField(
            model_name='decret_executif',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.jarida'),
        ),
    ]
