# Generated by Django 2.1.2 on 2018-11-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_auto_20181106_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decret_executif',
            name='loi',
        ),
    ]
