# Generated by Django 2.1.2 on 2018-11-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_arrete_arrete_interministeriel_decision_decret_presidentiel_ordonnance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrete',
            name='objet',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='arrete_interministeriel',
            name='objet',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='decision',
            name='objet',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='decret_executif',
            name='objet',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='decret_presidentiel',
            name='objet',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='loi',
            name='objet',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='objet',
            field=models.TextField(max_length=2000),
        ),
    ]
